# Feature Engineering

In [20]:
import pandas as pd

In [21]:
#All the leagues
premier = pd.read_csv("../initial_data/leagues/premier_league_stats.csv")
bundesliga = pd.read_csv("../initial_data/leagues/bundesliga_league_stats.csv")
eredivise = pd.read_csv("../initial_data/leagues/eredivise_league_stats.csv")
ligue1 = pd.read_csv("../initial_data/leagues/ligue1_league_stats.csv")
seriea = pd.read_csv("../initial_data/leagues/seria_league_stats.csv")
laliga = pd.read_csv("../initial_data/leagues/laliga_league_stats.csv")
cl = pd.read_csv("../initial_data/cl/champions_league_stats.csv")

Form Score

In [22]:
def form_score(df):
    df["Form Score (Last 5)"] = (df["Won"] * 3 + (df["Played"] - df["Won"] - df["Lost"]) * 1) / df["Played"]
form_score(premier)
form_score(bundesliga)
form_score(eredivise)
form_score(ligue1)
form_score(seriea)
form_score(laliga)
form_score(cl)

premier.head()

,Position,Team,Played,Won,Lost,Points,Goals For,Goals Against,Goal Difference,Power Score,...,Home Wins,Home Losses,Home GF,Home GA,Away Played,Away Wins,Away Losses,Away GF,Away GA,Form Score (Last 5)
0,1,Liverpool FC,26,18,1,61,62,26,36,130.08,...,9,1,26,10,14,9,0,36,16,2.346154
1,2,Arsenal FC,26,15,3,53,51,23,28,105.23,...,8,1,27,11,13,7,2,24,12,2.038462
2,3,Nottingham Forest FC,25,14,6,47,41,29,12,70.80,...,7,2,22,10,13,7,4,19,19,1.880000
3,4,Manchester City FC,25,13,7,44,52,35,17,77.60,...,8,2,28,15,13,5,5,24,20,1.760000
4,5,AFC Bournemouth,26,12,7,43,44,30,14,67.62,...,6,4,17,10,13,6,3,27,20,1.653846

Home & Away Strength

In [23]:
def strength(df):
    df["Home Strength"] = df["Home Wins"] / df["Home Played"]
    df["Away Strength"] = df["Away Wins"] / df["Away Played"]
strength(premier)
strength(bundesliga)
strength(eredivise)
strength(ligue1)
strength(seriea)
strength(laliga)
strength(cl)

premier.head()

,Position,Team,Played,Won,Lost,Points,Goals For,Goals Against,Goal Difference,Power Score,...,Home GF,Home GA,Away Played,Away Wins,Away Losses,Away GF,Away GA,Form Score (Last 5),Home Strength,Away Strength
0,1,Liverpool FC,26,18,1,61,62,26,36,130.08,...,26,10,14,9,0,36,16,2.346154,0.750000,0.642857
1,2,Arsenal FC,26,15,3,53,51,23,28,105.23,...,27,11,13,7,2,24,12,2.038462,0.615385,0.538462
2,3,Nottingham Forest FC,25,14,6,47,41,29,12,70.80,...,22,10,13,7,4,19,19,1.880000,0.583333,0.538462
3,4,Manchester City FC,25,13,7,44,52,35,17,77.60,...,28,15,13,5,5,24,20,1.760000,0.666667,0.384615
4,5,AFC Bournemouth,26,12,7,43,44,30,14,67.62,...,17,10,13,6,3,27,20,1.653846,0.461538,0.461538

Goal Per Point

In [24]:
def goal_per_point(df):
    df["Goal Per Point"] = df["Points"] / df["Goals For"]

goal_per_point(premier)
goal_per_point(bundesliga)
goal_per_point(eredivise)
goal_per_point(ligue1)
goal_per_point(seriea)
goal_per_point(laliga)
goal_per_point(cl)

premier.head()

,Position,Team,Played,Won,Lost,Points,Goals For,Goals Against,Goal Difference,Power Score,...,Home GA,Away Played,Away Wins,Away Losses,Away GF,Away GA,Form Score (Last 5),Home Strength,Away Strength,Goal Per Point
0,1,Liverpool FC,26,18,1,61,62,26,36,130.08,...,10,14,9,0,36,16,2.346154,0.750000,0.642857,0.983871
1,2,Arsenal FC,26,15,3,53,51,23,28,105.23,...,11,13,7,2,24,12,2.038462,0.615385,0.538462,1.039216
2,3,Nottingham Forest FC,25,14,6,47,41,29,12,70.80,...,10,13,7,4,19,19,1.880000,0.583333,0.538462,1.146341
3,4,Manchester City FC,25,13,7,44,52,35,17,77.60,...,15,13,5,5,24,20,1.760000,0.666667,0.384615,0.846154
4,5,AFC Bournemouth,26,12,7,43,44,30,14,67.62,...,10,13,6,3,27,20,1.653846,0.461538,0.461538,0.977273

Attacking Strength

In [25]:
def attack(df):
    df["Attacking Strenght"] = df["Goals For"] / df["Played"]

attack(premier)
attack(bundesliga)
attack(eredivise)
attack(ligue1)
attack(seriea)
attack(laliga)
attack(cl)

premier.head()

,Position,Team,Played,Won,Lost,Points,Goals For,Goals Against,Goal Difference,Power Score,...,Away Played,Away Wins,Away Losses,Away GF,Away GA,Form Score (Last 5),Home Strength,Away Strength,Goal Per Point,Attacking Strenght
0,1,Liverpool FC,26,18,1,61,62,26,36,130.08,...,14,9,0,36,16,2.346154,0.750000,0.642857,0.983871,2.384615
1,2,Arsenal FC,26,15,3,53,51,23,28,105.23,...,13,7,2,24,12,2.038462,0.615385,0.538462,1.039216,1.961538
2,3,Nottingham Forest FC,25,14,6,47,41,29,12,70.80,...,13,7,4,19,19,1.880000,0.583333,0.538462,1.146341,1.640000
3,4,Manchester City FC,25,13,7,44,52,35,17,77.60,...,13,5,5,24,20,1.760000,0.666667,0.384615,0.846154,2.080000
4,5,AFC Bournemouth,26,12,7,43,44,30,14,67.62,...,13,6,3,27,20,1.653846,0.461538,0.461538,0.977273,1.692308

Defense Strength

In [26]:
def defense(df):
    df["Defense Strength"] = df["Goals Against"] / df["Played"]

defense(premier)
defense(bundesliga)
defense(eredivise)
defense(ligue1)
defense(seriea)
defense(laliga)
defense(cl)

premier.head()

,Position,Team,Played,Won,Lost,Points,Goals For,Goals Against,Goal Difference,Power Score,...,Away Wins,Away Losses,Away GF,Away GA,Form Score (Last 5),Home Strength,Away Strength,Goal Per Point,Attacking Strenght,Defense Strength
0,1,Liverpool FC,26,18,1,61,62,26,36,130.08,...,9,0,36,16,2.346154,0.750000,0.642857,0.983871,2.384615,1.000000
1,2,Arsenal FC,26,15,3,53,51,23,28,105.23,...,7,2,24,12,2.038462,0.615385,0.538462,1.039216,1.961538,0.884615
2,3,Nottingham Forest FC,25,14,6,47,41,29,12,70.80,...,7,4,19,19,1.880000,0.583333,0.538462,1.146341,1.640000,1.160000
3,4,Manchester City FC,25,13,7,44,52,35,17,77.60,...,5,5,24,20,1.760000,0.666667,0.384615,0.846154,2.080000,1.400000
4,5,AFC Bournemouth,26,12,7,43,44,30,14,67.62,...,6,3,27,20,1.653846,0.461538,0.461538,0.977273,1.692308,1.153846

Normalized Power Score

In [27]:
def normalize_power_score(df):
    df["Normalized Power Score"] = (df["Power Score"] - df["Power Score"].mean()) / df["Power Score"].std()

normalize_power_score(premier)
normalize_power_score(bundesliga)
normalize_power_score(eredivise)
normalize_power_score(ligue1)
normalize_power_score(seriea)
normalize_power_score(laliga)
normalize_power_score(cl)

premier.head()

,Position,Team,Played,Won,Lost,Points,Goals For,Goals Against,Goal Difference,Power Score,...,Away Losses,Away GF,Away GA,Form Score (Last 5),Home Strength,Away Strength,Goal Per Point,Attacking Strenght,Defense Strength,Normalized Power Score
0,1,Liverpool FC,26,18,1,61,62,26,36,130.08,...,0,36,16,2.346154,0.750000,0.642857,0.983871,2.384615,1.000000,1.851450
1,2,Arsenal FC,26,15,3,53,51,23,28,105.23,...,2,24,12,2.038462,0.615385,0.538462,1.039216,1.961538,0.884615,1.379814
2,3,Nottingham Forest FC,25,14,6,47,41,29,12,70.80,...,4,19,19,1.880000,0.583333,0.538462,1.146341,1.640000,1.160000,0.726357
3,4,Manchester City FC,25,13,7,44,52,35,17,77.60,...,5,24,20,1.760000,0.666667,0.384615,0.846154,2.080000,1.400000,0.855416
4,5,AFC Bournemouth,26,12,7,43,44,30,14,67.62,...,3,27,20,1.653846,0.461538,0.461538,0.977273,1.692308,1.153846,0.666003

Create Target Column

In [28]:
df = pd.read_csv("../Fixture/data/fixtures.csv")

In [29]:
#Last version of data for each league after feature engineering

premier.to_csv("../last_data/leagues/premier_league_stats.csv", index=False)
bundesliga.to_csv("../last_data/leagues/bundesliga_league_stats.csv", index=False)
eredivise.to_csv("../last_data/leagues/eredivise_league_stats.csv", index=False)
ligue1.to_csv("../last_data/leagues/ligue1_league_stats.csv", index=False)
seriea.to_csv("../last_data/leagues/seria_league_stats.csv", index=False)
laliga.to_csv("../last_data/leagues/laliga_league_stats.csv", index=False)
cl.to_csv("../last_data/cl/champions_league_stats.csv", index=False)